sudo: required
services:
  - docker

before_install:
  - docker build -t amruthsoft9/docker_react_proj -f Dockerfile.dev .

script:
  - docker run amruthsoft9/docker_react_proj npm run test -- --coverage
